Формат данных:

V1,V2,V3,V4,V5,V6,V7,V8,V9,V10

V1 - V9 : x,o

V10 : positive/negative

Let's see data

In [342]:
import pandas as pd

train = pd.read_csv('data/train1.csv');
test = pd.read_csv('data/test1.csv');

In [343]:
train.head()

  V1 V2 V3 V4 V5 V6 V7 V8 V9       V10
0  x  x  x  x  o  o  x  o  o  positive
1  x  x  x  x  o  o  o  o  x  positive
2  x  x  x  x  o  o  o  b  b  positive
3  x  x  x  x  o  o  b  o  b  positive
4  x  x  x  x  o  o  b  b  o  positive

In [344]:
test.head()

  V1 V2 V3 V4 V5 V6 V7 V8 V9       V10
0  x  x  x  x  o  o  o  x  o  positive
1  x  x  x  x  o  b  o  b  o  positive
2  x  x  x  o  o  x  o  x  o  positive
3  x  x  x  o  o  b  x  o  b  positive
4  x  x  x  b  o  b  o  o  x  positive

In [345]:
attributes = [
'topLeft', 'topMiddle', 'topRight',     
'middleLeft', 'middleMiddle', 'middleRight',
'botLeft', 'botMiddle', 'botRight',
'class'   
]

attributes

['topLeft',
 'topMiddle',
 'topRight',
 'middleLeft',
 'middleMiddle',
 'middleRight',
 'botLeft',
 'botMiddle',
 'botRight',
 'class']

Replace 'positive'/'negative' to 1/0 respectively.

In [346]:
train = train.replace('positive',1)
train = train.replace('negative',0)
train

    V1 V2 V3 V4 V5 V6 V7 V8 V9  V10
0    x  x  x  x  o  o  x  o  o    1
1    x  x  x  x  o  o  o  o  x    1
2    x  x  x  x  o  o  o  b  b    1
3    x  x  x  x  o  o  b  o  b    1
4    x  x  x  x  o  o  b  b  o    1
..  .. .. .. .. .. .. .. .. ..  ...
860  o  x  x  x  o  o  o  x  x    0
861  o  x  o  x  x  o  x  o  x    0
862  o  x  o  x  o  x  x  o  x    0
863  o  x  o  o  x  x  x  o  x    0
864  o  o  x  x  x  o  o  x  x    0

[865 rows x 10 columns]

In [347]:
train.columns = attributes

In [348]:
train

    topLeft topMiddle topRight middleLeft  ... botLeft botMiddle botRight class
0         x         x        x          x  ...       x         o        o     1
1         x         x        x          x  ...       o         o        x     1
2         x         x        x          x  ...       o         b        b     1
3         x         x        x          x  ...       b         o        b     1
4         x         x        x          x  ...       b         b        o     1
..      ...       ...      ...        ...  ...     ...       ...      ...   ...
860       o         x        x          x  ...       o         x        x     0
861       o         x        o          x  ...       x         o        x     0
862       o         x        o          x  ...       x         o        x     0
863       o         x        o          o  ...       x         o        x     0
864       o         o        x          x  ...       o         x        x     0

[865 rows x 10 columns]

In [349]:
train_x = train.loc[:, train.columns != 'class']
train_x

    topLeft topMiddle topRight  ... botLeft botMiddle botRight
0         x         x        x  ...       x         o        o
1         x         x        x  ...       o         o        x
2         x         x        x  ...       o         b        b
3         x         x        x  ...       b         o        b
4         x         x        x  ...       b         b        o
..      ...       ...      ...  ...     ...       ...      ...
860       o         x        x  ...       o         x        x
861       o         x        o  ...       x         o        x
862       o         x        o  ...       x         o        x
863       o         x        o  ...       x         o        x
864       o         o        x  ...       o         x        x

[865 rows x 9 columns]

In [350]:
train_y = train.iloc[:,-1:]
train_y

     class
0        1
1        1
2        1
3        1
4        1
..     ...
860      0
861      0
862      0
863      0
864      0

[865 rows x 1 columns]

In [351]:
def make_intent(example):
    global attributes
    return set([i+':'+str(k) for i, k in zip(attributes, example)])

Read data

In [307]:
def read_data(idx, idxt):  
    pluses, minuses=[],[]
    X_test,y_test=[],[]
    for i in range(idx):
        ii=str(i+1)
        f = open("data/train" + ii + ".csv", "r")
        train = [a.strip().split(",") for a in f]
        tmp1 = [make_intent(a[:-1]) for a in train if a[-1] == "positive"]
        tmp2 = [make_intent(a[:-1]) for a in train if a[-1] == "negative"]
        f.close()

        pluses+=tmp1
        minuses+=tmp2   
    for i in range(idxt):
        ii=str(i+1)
        f = open("data/test" + ii + ".csv", "r")
        _unknown = [a.strip().split(",") for a in f]

        tmp1 = [make_intent(a[:-1]) for a in _unknown]
        tmp2 = [1 if a[-1] == "positive" else 0 for a in _unknown ]
        del tmp1[0]
        del tmp2[0]
        f.close()
        X_test+=tmp1
        y_test+=tmp2
        
    return pluses, minuses, X_test, y_test

In [308]:
pluses, minuses, X_test, y_test = read_data(1,1)

In [309]:
print(pluses[:10])
print(minuses[:10])
print(X_test[:10])
print(y_test[:10])

[{'topLeft:x', 'middleRight:o', 'middleLeft:x', 'botLeft:x', 'topMiddle:x', 'botRight:o', 'botMiddle:o', 'topRight:x', 'middleMiddle:o'}, {'topLeft:x', 'botLeft:o', 'middleRight:o', 'middleLeft:x', 'botRight:x', 'topMiddle:x', 'botMiddle:o', 'topRight:x', 'middleMiddle:o'}, {'topLeft:x', 'botLeft:o', 'middleRight:o', 'botRight:b', 'botMiddle:b', 'middleLeft:x', 'topMiddle:x', 'topRight:x', 'middleMiddle:o'}, {'topLeft:x', 'middleRight:o', 'botRight:b', 'middleLeft:x', 'topMiddle:x', 'botMiddle:o', 'topRight:x', 'middleMiddle:o', 'botLeft:b'}, {'topLeft:x', 'middleRight:o', 'botMiddle:b', 'middleLeft:x', 'topMiddle:x', 'botRight:o', 'topRight:x', 'middleMiddle:o', 'botLeft:b'}, {'topLeft:x', 'middleRight:b', 'botLeft:o', 'botRight:b', 'middleLeft:x', 'topMiddle:x', 'botMiddle:o', 'topRight:x', 'middleMiddle:o'}, {'topLeft:x', 'middleRight:b', 'middleLeft:x', 'topMiddle:x', 'botRight:o', 'botMiddle:o', 'topRight:x', 'middleMiddle:o', 'botLeft:b'}, {'topLeft:x', 'botLeft:o', 'middleRight:o', 'botRight:b', 'middleLeft:x', 'middleMiddle:b', 'topMiddle:x', 'botMiddle:o', 'topRight:x'}, {'topLeft:x', 'botLeft:o', 'middleRight:o', 'botMiddle:b', 'middleLeft:x', 'middleMiddle:b', 'topMiddle:x', 'botRight:o', 'topRight:x'}, {'topLeft:x', 'middleRight:o', 'middleLeft:x', 'middleMiddle:b', 'topMiddle:x', 'botRight:o', 'botMiddle:o', 'topRight:x', 'botLeft:b'}]
[{'topLeft:x', 'topRight:o', 'botLeft:o', 'middleRight:o', 'botMiddle:b', 'middleLeft:x', 'topMiddle:x', 'botRight:o', 'middleMiddle:x'}, {'topLeft:x', 'topRight:o', 'middleRight:o', 'middleLeft:x', 'topMiddle:x', 'botRight:o', 'botMiddle:o', 'middleMiddle:x', 'botLeft:b'}, {'topLeft:x', 'topRight:o', 'middleRight:b', 'botLeft:o', 'middleLeft:x', 'topMiddle:x', 'botRight:o', 'botMiddle:o', 'middleMiddle:x'}, {'topLeft:x', 'topRight:o', 'botLeft:o', 'botMiddle:b', 'middleLeft:x', 'topMiddle:x', 'botRight:o', 'middleRight:x', 'middleMiddle:o'}, {'topLeft:x', 'topRight:o', 'botLeft:o', 'middleRight:o', 'botRight:b', 'botMiddle:x', 'middleLeft:x', 'topMiddle:x', 'middleMiddle:o'}, {'topLeft:x', 'topRight:o', 'botLeft:o', 'middleRight:o', 'botMiddle:b', 'middleLeft:x', 'botRight:x', 'topMiddle:x', 'middleMiddle:o'}, {'topLeft:x', 'topRight:o', 'middleRight:o', 'botMiddle:x', 'middleLeft:x', 'topMiddle:x', 'botRight:o', 'middleMiddle:o', 'botLeft:b'}, {'topLeft:x', 'topRight:o', 'middleRight:b', 'botLeft:o', 'botRight:b', 'botMiddle:b', 'middleLeft:x', 'topMiddle:x', 'middleMiddle:o'}, {'topLeft:x', 'topRight:o', 'botLeft:o', 'middleLeft:x', 'middleMiddle:b', 'topMiddle:x', 'botRight:o', 'botMiddle:o', 'middleRight:x'}, {'topLeft:x', 'topRight:o', 'botLeft:o', 'middleRight:o', 'botMiddle:x', 'middleLeft:x', 'middleMiddle:b', 'topMiddle:x', 'botRight:o'}]
[{'topLeft:x', 'botLeft:o', 'middleRight:o', 'botMiddle:x', 'middleLeft:x', 'topMiddle:x', 'botRight:o', 'topRight:x', 'middleMiddle:o'}, {'topLeft:x', 'middleRight:b', 'botLeft:o', 'botMiddle:b', 'middleLeft:x', 'topMiddle:x', 'botRight:o', 'topRight:x', 'middleMiddle:o'}, {'topLeft:x', 'botLeft:o', 'botMiddle:x', 'topMiddle:x', 'botRight:o', 'middleRight:x', 'topRight:x', 'middleMiddle:o', 'middleLeft:o'}, {'topLeft:x', 'middleRight:b', 'botRight:b', 'botLeft:x', 'topMiddle:x', 'botMiddle:o', 'topRight:x', 'middleMiddle:o', 'middleLeft:o'}, {'topLeft:x', 'middleLeft:b', 'middleRight:b', 'botLeft:o', 'botRight:x', 'topMiddle:x', 'botMiddle:o', 'topRight:x', 'middleMiddle:o'}, {'topLeft:x', 'middleLeft:b', 'middleRight:o', 'botRight:b', 'middleMiddle:b', 'topMiddle:x', 'botMiddle:o', 'topRight:x', 'botLeft:b'}, {'topLeft:x', 'topRight:o', 'botLeft:o', 'middleRight:o', 'botMiddle:x', 'botRight:x', 'topMiddle:x', 'middleMiddle:x', 'middleLeft:o'}, {'topLeft:x', 'topRight:o', 'middleRight:b', 'botLeft:o', 'botRight:b', 'botMiddle:x', 'topMiddle:x', 'middleMiddle:x', 'middleLeft:o'}, {'topLeft:x', 'middleRight:o', 'botRight:b', 'middleLeft:x', 'botLeft:x', 'topMiddle:x', 'botMiddle:o', 'topRight:b', 'middleMiddle:o'}, {'topLeft:x', 'middleRight:o', 'botLeft:b', 'botRight:x', 'topMiddle:x', 'botMiddle:o', 'middleMiddle:x', 'topRight:b', 'middleLeft:o'}]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

Algorithm norm sum of power of features intersection with positive and negative.

Get value that is bigger.

In [301]:
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
np.seterr(divide='ignore', invalid='ignore')

TP1 = 0
TN1 = 0
FP1 = 0
FN1 = 0
TPR1 = 0
TNR1 = 0
FPR1 = 0
NPV1 = 0
FDR1 = 0
acc1 = 0
prec1 = 0
rec1 = 0
def algorithm0(pluses, minuses, X, y):
    global TP1
    global TN1
    global FP1
    global FN1
    global TPR1
    global TNR1
    global FPR1
    global NPV1
    global FDR1
    global acc1
    global prec1
    global rec1
    y_pred=[]
    for x in X:
        positive=0
        negative=0

        for p in pluses:
            res=p & x
            positive+=float(len(res)) / len(p)
        positive=float(positive) / len(pluses) 

        for m in minuses:
            res=m & x
            negative+=float(len(res)) / len(m)
        negative=float(negative) / len(minuses) 

        if (positive > negative):
          y_pred.append(1)
        else:
          y_pred.append(0)

    y_pred = np.array(y_pred)

    TP = np.sum(y * y_pred)
    TN = np.sum(y + y_pred == 0)
    FP = np.sum((y  == 0) * (y_pred == 1))
    FN = np.sum((y  == 1) * (y_pred == 0))
    TPR = float(TP) / np.sum(y == 1)
    TNR = float(TN) / np.sum(y == 0)
    FPR = float(FP) / (TP + FN)
    NPV = float(TN) / (TN + FN)
    FDR = float(FP) / (TP + FP)
    acc = accuracy_score(y, y_pred)
    prec = precision_score(y, y_pred)
    rec = recall_score(y, y_pred)

    TP1 += TP
    TN1 += TN
    FP1 += FP
    FN1 += FN
    TPR1 += TPR
    TNR1 += TNR
    FPR1 += FPR
    NPV1 += NPV
    FDR1 += FDR
    acc1 += acc
    prec1 += prec
    rec1 += rec

    print ("True Positive: {}\nTrue Negative: {}\nFalse Positive: {}\n\
False Negative: {}\nTrue Positive Rate: {}\nTrue Negative Rate: {}\n\
Negative Predictive Value: {}\nFalse Positive Rate: {}\nFalse Discovery Rate: {}\nAccuracy:{}\nPrecision: {}\n\
Recall: {}".format(TP, TN, FP, FN, TPR, TNR, FPR, NPV, FDR, acc, prec, rec))
    
    return accuracy_score(np.array(y), np.array(y_pred))

In [302]:
print('Algorithm0:')
avg = 0
for i in range(1,11):
    print ('Train set: ', i)
    plus, minus, x_test, y_test = read_data(i,i)
    pred=algorithm0(plus, minus, x_test, y_test)
    avg +=pred
    print('Test accuracy: ', round(pred,5))
    print()
print("Average TP: ", TP1/10)
print("Average TN: ", TN1/10)
print("Average FP: ", FP1/10)
print("Average FN: ", FN1/10)
print("Average TPR: ", TPR1/10)
print("Average TNR: ", TNR1/10)
print("Average FPR: ", FPR1/10)
print("Average NPV: ", NPV1/10)
print("Average FDR: ", FDR1/10)

print("Average accuracy: ", acc1/10)
print("Average recall: ", prec1/10)
print("Average recall: ", rec1/10)

Algorithm0:
Train set:  1
True Positive: 34
True Negative: 24
False Positive: 0
False Negative: 0
True Positive Rate: inf
True Negative Rate: inf
Negative Predictive Value: 0.0
False Positive Rate: 1.0
False Discovery Rate: 0.0
Accuracy:0.6236559139784946
Precision: 0.8095238095238095
Recall: 0.5573770491803278
Test accuracy:  0.62366

Train set:  2
True Positive: 67
True Negative: 47
False Positive: 0
False Negative: 0
True Positive Rate: inf
True Negative Rate: inf
Negative Predictive Value: 0.0
False Positive Rate: 1.0
False Discovery Rate: 0.0
Accuracy:0.6333333333333333
Precision: 0.7613636363636364
Recall: 0.5982142857142857
Test accuracy:  0.63333

Train set:  3
True Positive: 111
True Negative: 74
False Positive: 0
False Negative: 0
True Positive Rate: inf
True Negative Rate: inf
Negative Predictive Value: 0.0
False Positive Rate: 1.0
False Discovery Rate: 0.0
Accuracy:0.6607142857142857
Precision: 0.7928571428571428
Recall: 0.6271186440677966
Test accuracy:  0.66071

Train set:  4
True Positive: 145
True Negative: 94
False Positive: 0
False Negative: 0
True Positive Rate: inf
True Negative Rate: inf
Negative Predictive Value: 0.0
False Positive Rate: 1.0
False Discovery Rate: 0.0
Accuracy:0.6476964769647696
Precision: 0.7880434782608695
Recall: 0.614406779661017
Test accuracy:  0.6477

Train set:  5
True Positive: 185
True Negative: 110
False Positive: 0
False Negative: 0
True Positive Rate: inf
True Negative Rate: inf
Negative Predictive Value: 0.0
False Positive Rate: 1.0
False Discovery Rate: 0.0
Accuracy:0.6441048034934498
Precision: 0.7872340425531915
Recall: 0.6208053691275168
Test accuracy:  0.6441

Train set:  6
True Positive: 222
True Negative: 130
False Positive: 0
False Negative: 0
True Positive Rate: inf
True Negative Rate: inf
Negative Predictive Value: 0.0
False Positive Rate: 1.0
False Discovery Rate: 0.0
Accuracy:0.6482504604051565
Precision: 0.7900355871886121
Recall: 0.6271186440677966
Test accuracy:  0.64825

Train set:  7
True Positive: 266
True Negative: 165
False Positive: 0
False Negative: 0
True Positive Rate: inf
True Negative Rate: inf
Negative Predictive Value: 0.0
False Positive Rate: 1.0
False Discovery Rate: 0.0
Accuracy:0.6560121765601218
Precision: 0.7964071856287425
Recall: 0.6273584905660378
Test accuracy:  0.65601

Train set:  8
True Positive: 318
True Negative: 188
False Positive: 0
False Negative: 0
True Positive Rate: inf
True Negative Rate: inf
Negative Predictive Value: 0.0
False Positive Rate: 1.0
False Discovery Rate: 0.0
Accuracy:0.662303664921466
Precision: 0.801007556675063
Recall: 0.6398390342052314
Test accuracy:  0.6623

Train set:  9
True Positive: 373
True Negative: 210
False Positive: 0
False Negative: 0
True Positive Rate: inf
True Negative Rate: inf
Negative Predictive Value: 0.0
False Positive Rate: 1.0
False Discovery Rate: 0.0
Accuracy:0.6724336793540946
Precision: 0.8056155507559395
Recall: 0.6578483245149912
Test accuracy:  0.67243

Train set:  10
True Positive: 409
True Negative: 236
False Positive: 0
False Negative: 0
True Positive Rate: inf
True Negative Rate: inf
Negative Predictive Value: 0.0
False Positive Rate: 1.0
False Discovery Rate: 0.0
Accuracy:0.673277661795407
Precision: 0.80990099009901
Recall: 0.6533546325878594
Test accuracy:  0.67328

Average TP:  213.0
Average TN:  127.8
Average FP:  0.0
Average FN:  0.0
Average TPR:  inf
Average TNR:  inf
Average FPR:  0.0
Average NPV:  1.0
Average FDR:  0.0
Average accuracy:  0.652178245652058
Average recall:  0.7941988979906016
Average recall:  0.6223441253692861

Algorithm 2

In [252]:
import pandas as pd

train = pd.read_csv('data/train1.csv');
test = pd.read_csv('data/test1.csv');

train = train.replace('positive',1)
train = train.replace('negative',0)
y  = np.array(train['V10'])
del train['V10']
train = pd.get_dummies(train)
train

     V1_b  V1_o  V1_x  V2_b  V2_o  V2_x  ...  V8_b  V8_o  V8_x  V9_b  V9_o  V9_x
0       0     0     1     0     0     1  ...     0     1     0     0     1     0
1       0     0     1     0     0     1  ...     0     1     0     0     0     1
2       0     0     1     0     0     1  ...     1     0     0     1     0     0
3       0     0     1     0     0     1  ...     0     1     0     1     0     0
4       0     0     1     0     0     1  ...     1     0     0     0     1     0
..    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
860     0     1     0     0     0     1  ...     0     0     1     0     0     1
861     0     1     0     0     0     1  ...     0     1     0     0     0     1
862     0     1     0     0     0     1  ...     0     1     0     0     0     1
863     0     1     0     0     0     1  ...     0     1     0     0     0     1
864     0     1     0     0     1     0  ...     0     0     1     0     0     1

[865 rows x 27 columns]

In [300]:
print('Algorithm2:')
avg = 0
TP1 = 0
TN1 = 0
FP1 = 0
FN1 = 0
TPR1 = 0
TNR1 = 0
FPR1 = 0
NPV1 = 0
FDR1 = 0
acc1 = 0
prec1 = 0
rec1 = 0
for i in range(1,11):
    print ('Train set: ', i)
    train = pd.read_csv('data/test'+str(i)+'.csv')
    test = pd.read_csv('data/train'+str(i)+'.csv')
    train = train.replace('positive',1)
    train = train.replace('negative',0)
    y  = np.array(train['V10'])
    del train['V10']
    #train = pd.get_dummies(train)
    train =  np.array(pd.get_dummies(train)).astype(int)
    test = test.replace('positive',1)
    test = test.replace('negative',0)

    

    yT  = np.array(test['V10'])
    del test['V10']
    #test = pd.get_dummies(test)
    test =  np.array(pd.get_dummies(test)).astype(int)
    xpos = train[y == 1]
    xneg = train[y == 0]

    y_pred = []
    for t in test:
        pos = np.sum(t == xpos) / float(len(xpos))
        neg = np.sum(t == xneg) / float(len(xneg))
        if (pos > neg):
            y_pred.append(1)
        else:
            y_pred.append(0)

    y_pred = np.array(y_pred)
    
    TP = np.sum(yT * y_pred)
    TN = np.sum(yT + y_pred == 0)
    FP = np.sum((yT  == 0) * (y_pred == 1))
    FN = np.sum((yT  == 1) * (y_pred == 0))
    TPR = float(TP) / np.sum(yT == 1)
    TNR = float(TN) / np.sum(yT == 0)
    FPR = float(FP) / (TP + FN)
    NPV = float(TN) / (TN + FN)
    FDR = float(FP) / (TP + FP)
    acc = accuracy_score(yT, y_pred)
    prec = precision_score(yT, y_pred)
    rec = recall_score(yT, y_pred)
    avg +=acc

    TP1 += TP
    TN1 += TN
    FP1 += FP
    FN1 += FN
    TPR1 += TPR
    TNR1 += TNR
    FPR1 += FPR
    NPV1 += NPV
    FDR1 += FDR
    acc1 += acc
    prec1 += prec
    rec1 += rec
    print ("True Positive: {}\nTrue Negative: {}\nFalse Positive: {}\n\
False Negative: {}\nTrue Positive Rate: {}\nTrue Negative Rate: {}\n\
Negative Predictive Value: {}\nFalse Positive Rate: {}\nFalse Discovery Rate: {}\nAccuracy: {}\nPrecision: {}\n\
Recall: {}".format(TP, TN, FP, FN, TPR, TNR, FPR, NPV, FDR, acc, prec, rec))

print("Average TP: ", TP1/10)
print("Average TN: ", TN1/10)
print("Average FP: ", FP1/10)
print("Average FN: ", FN1/10)
print("Average TPR: ", TPR1/10)
print("Average TNR: ", TNR1/10)
print("Average FPR: ", FPR1/10)
print("Average NPV: ", NPV1/10)
print("Average FDR: ", FDR1/10)

print("Average accuracy: ", acc1/10)
print("Average recall: ", prec1/10)
print("Average recall: ", rec1/10)

print()
print("Average accuracy: ", avg/10)

Algorithm2:
Train set:  1
True Positive: 328
True Negative: 192
False Positive: 108
False Negative: 237
True Positive Rate: 0.5805309734513274
True Negative Rate: 0.64
Negative Predictive Value: 0.1911504424778761
False Positive Rate: 0.44755244755244755
False Discovery Rate: 0.24770642201834864
Accuracy: 0.6011560693641619
Precision: 0.7522935779816514
Recall: 0.5805309734513274
Train set:  2
True Positive: 352
True Negative: 202
False Positive: 94
False Negative: 223
True Positive Rate: 0.6121739130434782
True Negative Rate: 0.6824324324324325
Negative Predictive Value: 0.1634782608695652
False Positive Rate: 0.4752941176470588
False Discovery Rate: 0.21076233183856502
Accuracy: 0.6360505166475315
Precision: 0.7892376681614349
Recall: 0.6121739130434782
Train set:  3
True Positive: 357
True Negative: 197
False Positive: 100
False Negative: 204
True Positive Rate: 0.6363636363636364
True Negative Rate: 0.6632996632996633
Negative Predictive Value: 0.17825311942959002
False Positive Rate: 0.4912718204488778
False Discovery Rate: 0.2188183807439825
Accuracy: 0.6456876456876457
Precision: 0.7811816192560175
Recall: 0.6363636363636364
Train set:  4
True Positive: 336
True Negative: 228
False Positive: 74
False Negative: 231
True Positive Rate: 0.5925925925925926
True Negative Rate: 0.7549668874172185
Negative Predictive Value: 0.13051146384479717
False Positive Rate: 0.49673202614379086
False Discovery Rate: 0.18048780487804877
Accuracy: 0.6490218642117376
Precision: 0.8195121951219512
Recall: 0.5925925925925926
Train set:  5
True Positive: 351
True Negative: 208
False Positive: 97
False Negative: 213
True Positive Rate: 0.6223404255319149
True Negative Rate: 0.6819672131147541
Negative Predictive Value: 0.17198581560283688
False Positive Rate: 0.49406175771971494
False Discovery Rate: 0.21651785714285715
Accuracy: 0.6432681242807825
Precision: 0.7834821428571429
Recall: 0.6223404255319149
Train set:  6
True Positive: 351
True Negative: 208
False Positive: 95
False Negative: 219
True Positive Rate: 0.6157894736842106
True Negative Rate: 0.6864686468646864
Negative Predictive Value: 0.16666666666666666
False Positive Rate: 0.48711943793911006
False Discovery Rate: 0.21300448430493274
Accuracy: 0.6403207331042382
Precision: 0.7869955156950673
Recall: 0.6157894736842106
Train set:  7
True Positive: 350
True Negative: 190
False Positive: 98
False Negative: 206
True Positive Rate: 0.6294964028776978
True Negative Rate: 0.6597222222222222
Negative Predictive Value: 0.17625899280575538
False Positive Rate: 0.4797979797979798
False Discovery Rate: 0.21875
Accuracy: 0.6398104265402843
Precision: 0.78125
Recall: 0.6294964028776978
Train set:  8
True Positive: 357
True Negative: 184
False Positive: 114
False Negative: 196
True Positive Rate: 0.6455696202531646
True Negative Rate: 0.6174496644295302
Negative Predictive Value: 0.20614828209764918
False Positive Rate: 0.4842105263157895
False Discovery Rate: 0.24203821656050956
Accuracy: 0.63572267920094
Precision: 0.7579617834394905
Recall: 0.6455696202531646
Train set:  9
True Positive: 338
True Negative: 203
False Positive: 96
False Negative: 218
True Positive Rate: 0.6079136690647482
True Negative Rate: 0.6789297658862876
Negative Predictive Value: 0.17266187050359713
False Positive Rate: 0.4821852731591449
False Discovery Rate: 0.22119815668202766
Accuracy: 0.632748538011696
Precision: 0.7788018433179723
Recall: 0.6079136690647482
Train set:  10
True Positive: 379
True Negative: 197
False Positive: 103
False Negative: 188
True Positive Rate: 0.6684303350970018
True Negative Rate: 0.6566666666666666
Negative Predictive Value: 0.18165784832451498
False Positive Rate: 0.5116883116883116
False Discovery Rate: 0.21369294605809128
Accuracy: 0.6643598615916955
Precision: 0.7863070539419087
Recall: 0.6684303350970018
Average TP:  349.9
Average TN:  200.9
Average FP:  97.9
Average FN:  213.5
Average TPR:  0.6211201041959772
Average TNR:  0.6721903162333461
Average FPR:  0.17387727626228489
Average NPV:  0.4849913698412226
Average FDR:  0.21829766002273635
Average accuracy:  0.6388146458640713
Average recall:  0.7817023399772637
Average recall:  0.6211201041959772

Average accuracy:  0.6388146458640713

In [331]:
TP1 = 0
TN1 = 0
FP1 = 0
FN1 = 0
TPR1 = 0
TNR1 = 0
FPR1 = 0
NPV1 = 0
FDR1 = 0
acc1 = 0
prec1 = 0
rec1 = 0
def algo3(pluses, minuses, X, y, param):
    global TP1
    global TN1
    global FP1
    global FN1
    global TPR1
    global TNR1
    global FPR1
    global NPV1
    global FDR1
    global acc1
    global prec1
    global rec1
    y_pred=[]
    for t in X:
        
        positive=0
        negative=0

        for p in pluses:
            res=p & t
            if len(res)!=0:
                rate=0.0
                for k in pluses:
                    if k.issuperset(res) and k!=p:
                        rate+=1
                if rate>param:
                    positive+= float(rate) / len(pluses) * float(len(res)) / len(p)
                        
        positive=  float(positive) / len(pluses) 

        for m in minuses:
            res=m & t
            if len(res)!=0:
                rate=0
                for k in minuses :
                    if k.issuperset(res) and k!=m:
                        rate+=1
                if rate>param:        
                    negative+=float(rate) / len(minuses) * float(len(res)) / len(m) 
                
        negative =  float(negative) / len(minuses) 
        
           
        if (positive > negative):
            y_pred.append(1)
        else:
            if (positive< negative):
                y_pred.append(0)
            else:
                y_pred.append(0.5)

    y_pred = np.array(y_pred)

    TP = np.sum(y * y_pred)
    TN = np.sum(y + y_pred == 0)
    FP = np.sum((y  == 0) * (y_pred == 1))
    FN = np.sum((y  == 1) * (y_pred == 0))
    TPR = float(TP) / np.sum(y == 1)
    TNR = float(TN) / np.sum(y == 0)
    FPR = float(FP) / (TP + FN)
    NPV = float(TN) / (TN + FN)
    FDR = float(FP) / (TP + FP)
    acc = accuracy_score(y, y_pred)
    prec = precision_score(y, y_pred)
    rec = recall_score(y, y_pred)

    TP1 += TP
    TN1 += TN
    FP1 += FP
    FN1 += FN
    TPR1 += TPR
    TNR1 += TNR
    FPR1 += FPR
    NPV1 += NPV
    FDR1 += FDR
    acc1 += acc
    prec1 += prec
    rec1 += rec

  
    return accuracy_score(np.array(y), np.array(y_pred))

In [338]:
print('Algorithm3:')
avg = 0;
for i in range(1,11):
    plus, minus, x_test, y_test = read_data(i,i)
    pred=algo3(plus, minus, x_test, y_test, 8)
    avg+=pred

Algorithm3:

In [339]:
print('Average accuracy: ',avg/10)

Average accuracy:  0.97977